--Top Performing Stores

SELECT
    STORE_ID,
    SUM(WEEKLY_SALES) AS TOTAL_SALES
FROM FACT_SALES F
    JOIN DIM_STORE D
    ON F.STORE_KEY = D.STORE_KEY
GROUP BY STORE_ID
ORDER BY TOTAL_SALES DESC;

--Monthly Sales Trend

SELECT
    YEAR_MONTH,
    SUM(WEEKLY_SALES) AS TOTAL_SALES
FROM FACT_SALES F
    JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY YEAR_MONTH
ORDER BY YEAR_MONTH;

--Holiday Impact

SELECT
    IS_HOLIDAY,
    SUM(WEEKLY_SALES) AS TOTAL_SALES,
    AVG(WEEKLY_SALES) AS AVG_SALES
FROM FACT_SALES
GROUP BY IS_HOLIDAY;

--Store Type Analysis

SELECT
    TYPE,
    SUM(WEEKLY_SALES) AS TOTAL_SALES
FROM FACT_SALES F
    JOIN DIM_STORE D
    ON F.STORE_KEY = D.STORE_KEY
GROUP BY TYPE
ORDER BY TOTAL_SALES DESC;

--Department Performance

SELECT
    DEPARTMENT_ID,
    SUM(WEEKLY_SALES) AS TOTAL_SALES
FROM FACT_SALES F
    JOIN DIM_DEPARTMENT D
    ON F.DEPARTMENT_KEY = D.DEPARTMENT_KEY
GROUP BY DEPARTMENT_ID
ORDER BY TOTAL_SALES DESC;

--Quarterly Sales

SELECT
    QUARTER,
    SUM(WEEKLY_SALES) AS TOTAL_SALES
FROM FACT_SALES F
    JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY QUARTER
ORDER BY QUARTER;