USE DATABASE RETAIL_LAKEHOUSE_DB;
USE SCHEMA PUBLIC;

-- ====================================
-- DIM_STORE
-- ====================================

CREATE OR REPLACE TABLE DIM_STORE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY STORE) AS STORE_KEY,
    STORE AS STORE_ID,
    TYPE,
    SIZE
FROM SILVER.STORES;

-- ====================================
-- DIM_DEPARTMENT
-- ====================================

CREATE OR REPLACE TABLE DIM_DEPARTMENT AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY DEPT) AS DEPARTMENT_KEY,
    DEPT AS DEPARTMENT_ID
FROM SILVER.SALES;

-- ====================================
-- DIM_DATE
-- ====================================

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY DATE) AS DATE_KEY,
    DATE AS DATE_VALUE,
    YEAR(DATE) AS YEAR,
    MONTH(DATE) AS MONTH,
    QUARTER(DATE) AS QUARTER,
    DAYNAME(DATE) AS DAY_OF_WEEK,
    TO_CHAR(DATE,'MON') AS MONTH_NAME,
    TO_CHAR(DATE,'YYYY-MM') AS YEAR_MONTH,
    WEEK(DATE) AS WEEK_OF_YEAR
FROM SILVER.SALES;

-- ====================================
-- FACT_SALES
-- ====================================

CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    DS.STORE_KEY,
    DD.DEPARTMENT_KEY,
    DT.DATE_KEY,
    S.WEEKLY_SALES,
    S.IS_HOLIDAY
FROM SILVER.SALES S
    JOIN DIM_STORE DS
    ON S.STORE = DS.STORE_ID
    JOIN DIM_DEPARTMENT DD
    ON S.DEPT = DD.DEPARTMENT_ID
    JOIN DIM_DATE DT
    ON S.DATE = DT.DATE_VALUE;